import { BASE_CHAR } from 'ritzy/lib/core/RichText'

function insertChars(replica, value, attributes, position) {
  replica.insertCharsAt(position, value, attributes)

  let relativeMove = value.length
  return replica.getCharRelativeTo(position, relativeMove)
}

function insertCharsBatch(replica, insertPosition, chunks) {
  chunks.forEach(c => {
    insertPosition = insertChars(replica, c.text, c.attrs || {}, insertPosition)
  })
}

export default function createReplica(Swarm, id) {
  // create a SwarmClient with a userid of 'server' to populate the initial data
  let replica = new Swarm.Text(id)
  let content = [
    { 'text': 'This is ', 'attrs': null },
    { 'text': 'instance ' + id, 'attrs': {'italic': true} },
    { 'text': ' of the open source real-time collaborative ', 'attrs': {} },
    { 'text': 'Ritzy editor', 'attrs': {'bold': true, 'italic': true, 'underline': true} },
    { 'text': '. The contents are unique to the id above, so feel free to play and make changes.', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'Shortcuts', 'attrs': {'bold': true, 'underline': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'There is no toolbar yet, but you can use ', 'attrs': null },
    { 'text': 'keyboard shortcuts', 'attrs': {'underline': true} },
    { 'text': ' for selections and navigation:', 'attrs': {'underline': false} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': null },
    { 'text': 'Arrow keys', 'attrs': {'italic': true} },
    { 'text': ' or ', 'attrs': null },
    { 'text': 'mouse single-click', 'attrs': {'italic': true} },
    { 'text': ': cursor navigation', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': {} },
    { 'text': 'Ctrl-Home', 'attrs': {'italic': true} },
    { 'text': ', ', 'attrs': {} },
    { 'text': 'Ctrl-End', 'attrs': {'italic': true} },
    { 'text': ', ', 'attrs': {} },
    { 'text': 'Home', 'attrs': {'italic': true} },
    { 'text': ', ', 'attrs': {} },
    { 'text': 'End', 'attrs': {'italic': true} },
    { 'text': ': editor and line begin/end navigation', 'attrs': {} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': {} },
    { 'text': 'Ctrl-Left', 'attrs': {'italic': true} },
    { 'text': ', ', 'attrs': {} },
    { 'text': 'Ctrl-Right', 'attrs': {'italic': true} },
    { 'text': ':  word navigation', 'attrs': {} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': {} },
    { 'text': 'PgUp', 'attrs': {'italic': true} },
    { 'text': ', ', 'attrs': {} },
    { 'text': 'PgDown', 'attrs': {'italic': true} },
    { 'text': ': navigate up or down by 10 lines', 'attrs': {} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* Any navigation key or mouse click', 'attrs': {'italic': true} },
    { 'text': ' with ', 'attrs': {} },
    { 'text': 'shift', 'attrs': {'italic': true} },
    { 'text': ': create/modify selection', 'attrs': {} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': null },
    { 'text': 'Ctrl+A', 'attrs': {'italic': true} },
    { 'text': ': select the entire editor contents', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': null },
    { 'text': 'Ctrl+Backspace', 'attrs': {'italic': true} },
    { 'text': ', ', 'attrs': null },
    { 'text': 'Ctrl+Delete', 'attrs': {'italic': true} },
    { 'text': ': Back and forward word deletion', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'And for formatting, each of these toggle formatting for active selections, or alternately the active formatting at the cursor position:', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': null },
    { 'text': 'Ctrl+B', 'attrs': {'italic': true} },
    { 'text': ': ', 'attrs': {'italic': false} },
    { 'text': 'Bold', 'attrs': {'bold': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': null },
    { 'text': 'Ctrl+I', 'attrs': {'italic': true} },
    { 'text': ': ', 'attrs': {'italic': false} },
    { 'text': 'Italic', 'attrs': {'italic': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': {'italic': false} },
    { 'text': 'Ctrl+U', 'attrs': {'italic': true} },
    { 'text': ': ', 'attrs': {'italic': false} },
    { 'text': 'Underline', 'attrs': {'italic': false, 'underline': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': null },
    { 'text': 'Ctrl+.', 'attrs': {'italic': true} },
    { 'text': ': ', 'attrs': null },
    { 'text': 'Superscript', 'attrs': {'superscript': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': null },
    { 'text': 'Ctrl+,', 'attrs': {'italic': true} },
    { 'text': ': ', 'attrs': null },
    { 'text': 'Subscript', 'attrs': {'subscript': true} },
    { 'text': ' ', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': {} },
    { 'text': 'Alt+Shift+5', 'attrs': {'italic': true} },
    { 'text': ': ', 'attrs': null },
    { 'text': 'Strikethrough', 'attrs': {'strikethrough': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'Cool Stuff', 'attrs': {'bold': true, 'underline': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'Some things to note:', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* The ', 'attrs': null },
    { 'text': 'cursor', 'attrs': {'italic': true} },
    { 'text': ' blinks just like Word and Google Docs: when waiting for input, but not while typing or navigating. This type of thing is normally handled by the browser, but because Ritzy uses a custom surface and layout engine, here it is managed by Ritzy.', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* Speaking of the ', 'attrs': null },
    { 'text': 'cursor', 'attrs': {'italic': true} },
    { 'text': ': try ', 'attrs': null },
    { 'text': 'navigating to this italic text', 'attrs': {'italic': true} },
    { 'text': ' or using the italic ', 'attrs': {'italic': false} },
    { 'text': 'Ctrl+i', 'attrs': {'italic': true} },
    { 'text': ' shortcut. Note that the cursor slants. A simple thing, but user friendly. How many web editors have this other than Google Docs? This is possible because of the custom layout engine.', 'attrs': {'italic': false} },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': {} },
    { 'text': 'Real-time (and offline!) collaborative editing', 'attrs': {'italic': true} },
    { 'text': ': try copying and pasting the URL of this editor above into another window or browser. In a moment you should see a colored "remote cursor" in each editor (with a random name, the API will allow this to be set). Now navigate, select, and edit in one editor while watching the other. Try adding a third!', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': {} },
    { 'text': 'Selections', 'attrs': {'italic': true} },
    { 'text': ': Note that selection behavior, including end of line behavior with hard and soft returns, is very similar to Google Docs and Word. Try unfocusing the editor with an active selection and note that it "greys out". Try selecting overlapping text in this editor and a remote one.', 'attrs': {} },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': {} },
    { 'text': 'Copy/paste', 'attrs': {'italic': true} },
    { 'text': ': Try copy/pasting within the editor, to/from a text editor, and to/from Word or Google Docs. Pasting HTML copied from another browser tab works too.', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* ', 'attrs': null },
    { 'text': 'Editor scrolling', 'attrs': {'italic': true} },
    { 'text': ': The editor scrolls to follow the cursor.', 'attrs': {'italic': false} },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'API', 'attrs': {'bold': true, 'underline': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'This is a work in progress. Soon, we\'ll have some controls to the right that allow interacting with the editor via its API.', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'More Information', 'attrs': {'bold': true, 'underline': true} },
    { 'text': '\n', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': 'This is an early preview so there are still quite a few bugs. There is also some big stuff not implemented yet:', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* Undo/redo', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* Styles/fonts', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* Tables/bullets/numbering/images/links and other advanced formatting', 'attrs': null },
    { 'text': '\n', 'attrs': null },
    { 'text': '* See the Roadmap in the GitHub project README for more information', 'attrs': null}
  ]

  insertCharsBatch(replica, BASE_CHAR, content)
}
